# Generated by Django 4.2.6 on 2023-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iword', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='darkmode',
            field=models.BooleanField(default=False),
        ),
    ]
