# Generated by Django 4.2.6 on 2023-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iword', '0002_user_darkmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='prontype',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='PronunciationType',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
